// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/airbenders/profile/domain"
	mock "github.com/stretchr/testify/mock"
)

// StudentUseCase is an autogenerated mock type for the StudentUseCase type
type StudentUseCase struct {
	mock.Mock
}

// AddClasses provides a mock function with given fields: c, id, st
func (_m *StudentUseCase) AddClasses(c context.Context, id string, st *domain.Student) error {
	ret := _m.Called(c, id, st)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.Student) error); ok {
		r0 = rf(c, id, st)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CompleteClass provides a mock function with given fields: c, id, st
func (_m *StudentUseCase) CompleteClass(c context.Context, id string, st *domain.Student) error {
	ret := _m.Called(c, id, st)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.Student) error); ok {
		r0 = rf(c, id, st)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, st
func (_m *StudentUseCase) Create(ctx context.Context, st *domain.Student) error {
	ret := _m.Called(ctx, st)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Student) error); ok {
		r0 = rf(ctx, st)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateStudentTopic provides a mock function with given fields:
func (_m *StudentUseCase) CreateStudentTopic() {
	_m.Called()
}

// Delete provides a mock function with given fields: ctx, id
func (_m *StudentUseCase) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteStudentTopic provides a mock function with given fields:
func (_m *StudentUseCase) DeleteStudentTopic() {
	_m.Called()
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *StudentUseCase) GetByID(ctx context.Context, id string) (*domain.Student, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Student
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Student); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Student)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecommendedTeammates provides a mock function with given fields: ctx, id
func (_m *StudentUseCase) GetRecommendedTeammates(ctx context.Context, id string) ([]domain.Student, error) {
	ret := _m.Called(ctx, id)

	var r0 []domain.Student
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Student); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Student)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveClasses provides a mock function with given fields: c, id, st
func (_m *StudentUseCase) RemoveClasses(c context.Context, id string, st *domain.Student) error {
	ret := _m.Called(c, id, st)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.Student) error); ok {
		r0 = rf(c, id, st)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchStudents provides a mock function with given fields: ctx, st
func (_m *StudentUseCase) SearchStudents(ctx context.Context, st *domain.Student) ([]domain.Student, error) {
	ret := _m.Called(ctx, st)

	var r0 []domain.Student
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Student) []domain.Student); ok {
		r0 = rf(ctx, st)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Student)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.Student) error); ok {
		r1 = rf(ctx, st)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, st
func (_m *StudentUseCase) Update(ctx context.Context, id string, st *domain.Student) (*domain.Student, error) {
	ret := _m.Called(ctx, id, st)

	var r0 *domain.Student
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.Student) *domain.Student); ok {
		r0 = rf(ctx, id, st)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Student)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, *domain.Student) error); ok {
		r1 = rf(ctx, id, st)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStudentTopic provides a mock function with given fields:
func (_m *StudentUseCase) UpdateStudentTopic() {
	_m.Called()
}
